[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
universal_pvp = "4bdQ9U3yXD9EY2SxxMVasPmp5gw7RLtnc8yTkFZovmRR"

[programs.devnet]
universal_pvp = "4bdQ9U3yXD9EY2SxxMVasPmp5gw7RLtnc8yTkFZovmRR"

[programs.mainnet]
universal_pvp = "4bdQ9U3yXD9EY2SxxMVasPmp5gw7RLtnc8yTkFZovmRR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/universal_pvp"]

[test]
startup_wait = 10000

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899